name: birthday_tracker
description: A tracker of your contact's birthdays.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.3

  persistence:
    path: persistence
  persistence_hive_impl:
    path: persistence_hive_impl
  settings_service:
    path: settings_service
  settings_feature:
    path: settings_feature

  contacts_feature:
    path: contacts_feature
  contacts_repository:
    path: contacts_repository
  contacts_repository_impl:
    path: contacts_repository_impl
  contacts_service:
    path: contacts_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
