name: birthday_tracker
description: A tracker of your contact's birthdays.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  provider: ^6.0.3
  collection: ^1.16.0

  # Persistence
  persistence:
    path: persistence
  persistence_hive_impl:
    path: packages/persistence_hive_impl

  # Settings
  settings:
    path: settings

  # Contacts
  contacts:
    path: contacts
  contacts_impl:
    path: packages/contacts_impl

  # Contacts
  permissions:
    path: permissions
  permissions_impl:
    path: packages/permissions_impl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
