name: persistence_hive_impl
description: A new Flutter package project.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  persistence:
    path: ../../persistence

  hive: 2.2.3
  hive_flutter: ^1.1.0
  lazy_evaluation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

  hive_generator: ^1.1.3

